export const listings = [
  {
    title: "Modern Workspace in Tech Hub",
    owner: "Tech Innovations Inc.",
    image: `https://source.unsplash.com/random?workspace&number=1`,
    seating: 6,
    ownerContact: "info@techinnovations.com",
    rating: 4.8,
    reviews: 35,
    description: "A modern and collaborative workspace designed for creativity and productivity.",
    price: "$30 per hour",
    location: "Tech Hub Plaza, Silicon Valley",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 8 AM to 8 PM",
    term: "Flexible booking options available",
    category: "workspace"
  },
  {
    title: "Executive Desk with City View",
    owner: "Downtown Enterprises",
    image: `https://source.unsplash.com/random?workspace&number=2`,
    seating: 1,
    ownerContact: "info@downtownenterprises.com",
    rating: 4.6,
    reviews: 20,
    description: "An executive desk offering a stunning city view, perfect for focused work or meetings.",
    price: "$40 per hour",
    location: "Central Business District, Downtown",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 9 AM to 5 PM",
    term: "Hourly or daily bookings available",
    category: "desk"
  },
  {
    title: "Spacious Meeting Room",
    owner: "CollabZone Solutions",
    image: `https://source.unsplash.com/random?workspace&number=3`,
    seating: 12,
    ownerContact: "info@collabzone.com",
    rating: 4.9,
    reviews: 40,
    description: "A spacious meeting room equipped with state-of-the-art amenities for productive discussions and brainstorming sessions.",
    price: "$50 per hour",
    location: "Business Park Avenue, Suite 200",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 8 AM to 6 PM",
    term: "Flexible booking options available",
    category: "meetingRoom"
  },
  {
    title: "Private Office Suite",
    owner: "Elite Workspaces",
    image: `https://source.unsplash.com/random?workspace&number=4`,
    seating: 4,
    ownerContact: "info@eliteworkspaces.com",
    rating: 4.7,
    reviews: 25,
    description: "A fully furnished private office suite tailored for small teams or individuals seeking privacy and comfort.",
    price: "$80 per hour",
    location: "Executive Tower, Floor 15",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 9 AM to 7 PM",
    term: "Hourly or monthly rentals available",
    category: "privateOffice"
  },
  {
    title: "Collaborative Workspace",
    owner: "Creative Solutions Co.",
    image: `https://source.unsplash.com/random?workspace&number=5`,
    seating: 8,
    ownerContact: "info@creativesolutions.com",
    rating: 4.5,
    reviews: 30,
    description: "A vibrant and dynamic workspace designed to foster creativity and collaboration among professionals.",
    price: "$35 per hour",
    location: "Innovation Center, Suite 301",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 9 AM to 6 PM",
    term: "Flexible booking options available",
    category: "workspace"
  },
  {
    title: "Executive Desk with Harbor View",
    owner: "Seaside Offices Ltd.",
    image: `https://source.unsplash.com/random?workspace&number=6`,
    seating: 1,
    ownerContact: "info@seasideoffices.com",
    rating: 4.8,
    reviews: 18,
    description: "An exclusive executive desk offering breathtaking views of the harbor, ideal for focused work or client meetings.",
    price: "$45 per hour",
    location: "Marina Tower, Suite 501",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 8 AM to 6 PM",
    term: "Hourly or daily bookings available",
    category: "desk"
  },
  {
    title: "Elegant Boardroom",
    owner: "Corporate Solutions Inc.",
    image: `https://source.unsplash.com/random?workspace&number=7`,
    seating: 16,
    ownerContact: "info@corporatesolutions.com",
    rating: 4.9,
    reviews: 45,
    description: "An elegant boardroom equipped with advanced audiovisual technology for high-level presentations and meetings.",
    price: "$60 per hour",
    location: "Business Tower, Floor 10",
    isSmokingAllowed: false,
    availability: "Monday to Friday, 9 AM to 7 PM",
    term: "Flexible booking options available",
    category: "meetingRoom"
 
  }]